site_name: AR.js Documentation
nav:
    - Home: index.md
    - Image Tracking: image-tracking.md
    - Location Based: location-based.md
    - Marker Based: marker-based.md
    - UI and Events: ui-events.md
    - About: about.md
theme: flatly
